language: scala
scala:
- 2.11.8
before_script:
- curl -L -o $HOME/.sbt/launchers/0.13.11/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.11/sbt-launch.jar
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
jdk:
- oraclejdk7
branches:
  only:
  - master
env:
  global:
  - secure: YsOIDt6BoeMF/w7rN6xPj3XbiRwLA8oBoUAi1+VeS9dSnmYfnrMFvJxKAJoZrfKZ75wPIjuizDFpkbx7tX8szJDscds9rpA2WBMkq1PcPCjus2LPs9xZ2s0i/21v0LJuPU8c7jWbl7uOFzNcjBW6ttSivEA4U4B023m2VbJU9hLIrzpWRxH4tacbfIcklNEBvyiYVGk75ypXf3tGu5FnjSS1eAfNihRGF6DYJYH8SLREb4u/00Wj0bRZwP3Zk2Hzozf2TPB9crQYStxmSjTJXv9bHHFPJLuZEOsf3aJC8m17iB7947eLjTmtJv6rKe9d3ckG4Uh8xwI5ekHHmHI6MBsFIsOfMOMSqUmPDmaCixLgf82aaXKo5EvfrRGLnWw7hrRN0+pmGsNcS3Di2o9xn+pgUpMhDPX+TyWW21ZxOy7PWaQlvZoLuH/PMYYL/Z9+f+HZzHeCcaNkK0FyU1JScA64IKN/qtUkWeKc1ixqjFpVHTZS6rMtV0+je+URwVB3b4acPw2wYjE64LDl3sZ5weVFD77UlOtPSui0tRBRDG+X9JT/qNHKt7PbDi0qF/+XPRnF2Y/1y0ZsVA2xNocf6Z6fupJx7djK6RdpvpPOyeop3TViU6/5rwwoBI3s2RSkxgyjQ5DNgQZwDAtLFqJ4roLDyi47x26kuSqbAXrBn94=
  - secure: glSnoRs0ksfTqNgFrEnunVkZe+Ds7F4zKmwFykrydDg9wySZyiW7NBxJ+x2UvmPcGzaJAaIQ2dqAiwgtL0DGW8cllXCNra2N1P1RrgmR3wJdOaCicpreTmXlCgU7t817UPisWxDGgbzuA8HUSziAWew2gIAKBmdi3iOYFTpsnWmYZylUunrXRR9O4rcOy6Sm2pW2DXtvcP/xfc6hqEdlV4f+qsPl9z1HJFe4sFgfOJxFfibWXIb5z2X6ED+Ne4yFGq6BoTrvaHYlzddremZ98fsXVkDXVJmu1CyfAgkCjiZQTs80SKY/Hqcwewe25XLafWAkr9t1GA0PRKO1q4YNRs/AV0QOYdgeq6oNroDUqEt2QC4qH4G+ljogKgDnV1BdyQhd5KKwjBDgPEDY115JaXvYPgA8NVCsH7DJDxShCc6384Ce3tk4pjxXOhP2NGSyQ+sWhbihatapQc0+uvQYuuXvqYPQaQyriW3SSaOmwtSnWB5uRisEVq3iex8uAF8zkSa2yNP/YGapC/nXV7htVhy2A5DwUOAbklTzNBuQRjIPZrCe3/h21Frc1nDmV8uZEAtfAa6IZXcIyjP4vOJ6Rxd3J5MKrzWJ/2Sc2hCweEjJJpgDK6W0MbC0OlMuDlNxmHHagvZH7b40j0hB6iHDAMMwV7Mh6mQoWeTXcS8PFRU=
after_success:
  - >
      sbt publish
