package kafka.console.service.config.kafka.client

object Compression {

  private val _NO_COMP = "none"
  private val _GZIP    = "gzip"
  private val _SNAPPY  = "snappy"
  private val _LZ4     = "lz4"

  implicit def compressionToString(value: Compression): String = value match {
    case NoComp => _NO_COMP
    case GZip   => _GZIP
    case Snappy => _SNAPPY
    case Lz4    => _LZ4
  }
}

/**
 * The compression type for all data generated by the producer.
 */
sealed trait Compression

case object NoComp extends Compression
case object GZip   extends Compression
case object Snappy extends Compression
case object Lz4    extends Compression
